In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("tmdb_5000_movies.csv")

In [3]:
df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [4]:
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
df.tail()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

CHECKING NULL VALUES IN THE DATARFRAME

In [6]:
df.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

SELECTING CORRECT FEATURES AND MAKING IT A NEW DATAFRAME

In [7]:
final_df=df[["genres",'original_language','original_title',"popularity","production_companies","release_date",'tagline','vote_count','keywords','overview']]

In [8]:
final_df

,genres,original_language,original_title,popularity,production_companies,release_date,tagline,vote_count,keywords,overview
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",en,Avatar,150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",2009-12-10,Enter the World of Pandora.,11800,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",en,Pirates of the Caribbean: At World's End,139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2007-05-19,"At the end of the world, the adventure begins.",4500,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",en,Spectre,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2015-10-26,A Plan No One Escapes,4466,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",en,The Dark Knight Rises,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2012-07-16,The Legend Ends,9106,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",en,John Carter,43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,"Lost in our world, found in another.",2124,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...,...,...
4798,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",es,El Mariachi,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",1992-09-04,"He didn't come looking for trouble, but troubl...",238,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi just wants to play his guitar and ...
4799,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",en,Newlyweds,0.642552,[],2011-12-26,A newlywed couple's honeymoon is upended by th...,5,[],A newlywed couple's honeymoon is upended by th...
4800,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",en,"Signed, Sealed, Delivered",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",2013-10-13,NaN,6,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic..."
4801,[],en,Shanghai Calling,0.857008,[],2012-05-03,A New Yorker in Shanghai,7,[],When ambitious New York attorney Sam is sent t...
4802,"[{""id"": 99, ""name"": ""Documentary""}]",en,My Date with Drew,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",2005-08-05,NaN,16,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",Ever since the second grade when he first saw ...

### 🛠️ Converting String to List

I used the `ast.literal_eval()` function to safely evaluate stringified lists/dictionaries

In [9]:
import ast

 **Genres column**  
  Transforms each list of genre dictionaries into a comma‑separated string of genre names.

- **Production Companies column**  
  Similarly converts each list of production company dictionaries into a comma‑separated string of company names.

-**Keywords Column**
  Apply a lambda function to join all keyword names into a single comma‑separated string.

In [10]:


def convert_to_list(x):
    if isinstance(x, str):
        try:
            return ast.literal_eval(x)
        except Exception:
            return []
    return x
 
final_df['genres']=final_df['genres'].apply(convert_to_list)




final_df["genres"] = final_df["genres"].apply(lambda x: ", ".join(g['name'] for g in x)  if isinstance(x,list) else x)

In [11]:

def convert_to_list(x):
    if isinstance(x, str):
        try:
            return ast.literal_eval(x)
        except Exception:
            return []
    return x
 
final_df['production_companies']=final_df['production_companies'].apply(convert_to_list)

 **Genres column**  
  Transforms each list of genre dictionaries into a comma‑separated string of genre names.

- **Production Companies column**  
  Similarly converts each list of production company dictionaries into a comma‑separated string of company names.

-**Keywords Column**
  Apply a lambda function to join all keyword names into a single comma‑separated string.

In [12]:
final_df["production_companies"] = final_df["production_companies"].apply(lambda x: ", ".join(g['name'] for g in x)  if isinstance(x,list) else x)

In [13]:


def convert_to_list(x):
    if isinstance(x, str):
        try:
            return ast.literal_eval(x)
        except Exception:
            return []
    return x
 
final_df['keywords']=final_df['keywords'].apply(convert_to_list)

In [14]:
final_df["keywords"] = final_df["keywords"].apply(lambda x: ", ".join(g['name'] for g in x)  if isinstance(x,list) else x)

In [15]:
print((final_df["genres"].head()))

0    Action, Adventure, Fantasy, Science Fiction
1                     Adventure, Fantasy, Action
2                       Action, Adventure, Crime
3                 Action, Crime, Drama, Thriller
4             Action, Adventure, Science Fiction
Name: genres, dtype: str

In [16]:
final_df

,genres,original_language,original_title,popularity,production_companies,release_date,tagline,vote_count,keywords,overview
0,"Action, Adventure, Fantasy, Science Fiction",en,Avatar,150.437577,"Ingenious Film Partners, Twentieth Century Fox...",2009-12-10,Enter the World of Pandora.,11800,"culture clash, future, space war, space colony...","In the 22nd century, a paraplegic Marine is di..."
1,"Adventure, Fantasy, Action",en,Pirates of the Caribbean: At World's End,139.082615,"Walt Disney Pictures, Jerry Bruckheimer Films,...",2007-05-19,"At the end of the world, the adventure begins.",4500,"ocean, drug abuse, exotic island, east india t...","Captain Barbossa, long believed to be dead, ha..."
2,"Action, Adventure, Crime",en,Spectre,107.376788,"Columbia Pictures, Danjaq, B24",2015-10-26,A Plan No One Escapes,4466,"spy, based on novel, secret agent, sequel, mi6...",A cryptic message from Bond’s past sends him o...
3,"Action, Crime, Drama, Thriller",en,The Dark Knight Rises,112.312950,"Legendary Pictures, Warner Bros., DC Entertain...",2012-07-16,The Legend Ends,9106,"dc comics, crime fighter, terrorist, secret id...",Following the death of District Attorney Harve...
4,"Action, Adventure, Science Fiction",en,John Carter,43.926995,Walt Disney Pictures,2012-03-07,"Lost in our world, found in another.",2124,"based on novel, mars, medallion, space travel,...","John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...,...,...
4798,"Action, Crime, Thriller",es,El Mariachi,14.269792,Columbia Pictures,1992-09-04,"He didn't come looking for trouble, but troubl...",238,"united states–mexico barrier, legs, arms, pape...",El Mariachi just wants to play his guitar and ...
4799,"Comedy, Romance",en,Newlyweds,0.642552,,2011-12-26,A newlywed couple's honeymoon is upended by th...,5,,A newlywed couple's honeymoon is upended by th...
4800,"Comedy, Drama, Romance, TV Movie",en,"Signed, Sealed, Delivered",1.444476,"Front Street Pictures, Muse Entertainment Ente...",2013-10-13,NaN,6,"date, love at first sight, narration, investig...","""Signed, Sealed, Delivered"" introduces a dedic..."
4801,,en,Shanghai Calling,0.857008,,2012-05-03,A New Yorker in Shanghai,7,,When ambitious New York attorney Sam is sent t...
4802,Documentary,en,My Date with Drew,1.929883,"rusty bear entertainment, lucky crow films",2005-08-05,NaN,16,"obsession, camcorder, crush, dream girl",Ever since the second grade when he first saw ...

In [17]:
final_df["tagline"] = final_df["tagline"].apply(lambda x: ", ".join(g['name'] for g in x)  if isinstance(x,list) else x)

In [18]:
final_df["keywords"] = final_df["keywords"].apply(lambda x: ", ".join(g['name'] for g in x)  if isinstance(x,list) else x)

In [19]:
final_df["overview"] = final_df["overview"].apply(lambda x: ", ".join(g['name'] for g in x)  if isinstance(x,list) else x)

### 📝 Creating the Tags Column

To prepare text data for NLP tasks, we combine multiple descriptive fields into a single `tags` column:

- **Overview** – movie plot summary 

- **Genres** – cleaned genre names  

- **Tagline** – promotional tagline  

- **Keywords** – extracted keyword names  

- **Production Companies** – company names

By concatenating these, each movie gets one unified text field (`tags`) that captures its content, themes, and context.

### 📌 Purpose
- Creates a single feature for text vectorization.  

- Improves similarity search and recommendation models. 
 
- Simplifies preprocessing for NLP pipelines.

In [20]:
final_df['tags']=final_df['overview']+final_df['genres']+final_df['tagline']+final_df['keywords']+final_df['production_companies']

In [21]:
final_df

,genres,original_language,original_title,popularity,production_companies,release_date,tagline,vote_count,keywords,overview,tags
0,"Action, Adventure, Fantasy, Science Fiction",en,Avatar,150.437577,"Ingenious Film Partners, Twentieth Century Fox...",2009-12-10,Enter the World of Pandora.,11800,"culture clash, future, space war, space colony...","In the 22nd century, a paraplegic Marine is di...","In the 22nd century, a paraplegic Marine is di..."
1,"Adventure, Fantasy, Action",en,Pirates of the Caribbean: At World's End,139.082615,"Walt Disney Pictures, Jerry Bruckheimer Films,...",2007-05-19,"At the end of the world, the adventure begins.",4500,"ocean, drug abuse, exotic island, east india t...","Captain Barbossa, long believed to be dead, ha...","Captain Barbossa, long believed to be dead, ha..."
2,"Action, Adventure, Crime",en,Spectre,107.376788,"Columbia Pictures, Danjaq, B24",2015-10-26,A Plan No One Escapes,4466,"spy, based on novel, secret agent, sequel, mi6...",A cryptic message from Bond’s past sends him o...,A cryptic message from Bond’s past sends him o...
3,"Action, Crime, Drama, Thriller",en,The Dark Knight Rises,112.312950,"Legendary Pictures, Warner Bros., DC Entertain...",2012-07-16,The Legend Ends,9106,"dc comics, crime fighter, terrorist, secret id...",Following the death of District Attorney Harve...,Following the death of District Attorney Harve...
4,"Action, Adventure, Science Fiction",en,John Carter,43.926995,Walt Disney Pictures,2012-03-07,"Lost in our world, found in another.",2124,"based on novel, mars, medallion, space travel,...","John Carter is a war-weary, former military ca...","John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...,...,...,...
4798,"Action, Crime, Thriller",es,El Mariachi,14.269792,Columbia Pictures,1992-09-04,"He didn't come looking for trouble, but troubl...",238,"united states–mexico barrier, legs, arms, pape...",El Mariachi just wants to play his guitar and ...,El Mariachi just wants to play his guitar and ...
4799,"Comedy, Romance",en,Newlyweds,0.642552,,2011-12-26,A newlywed couple's honeymoon is upended by th...,5,,A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...
4800,"Comedy, Drama, Romance, TV Movie",en,"Signed, Sealed, Delivered",1.444476,"Front Street Pictures, Muse Entertainment Ente...",2013-10-13,NaN,6,"date, love at first sight, narration, investig...","""Signed, Sealed, Delivered"" introduces a dedic...",NaN
4801,,en,Shanghai Calling,0.857008,,2012-05-03,A New Yorker in Shanghai,7,,When ambitious New York attorney Sam is sent t...,When ambitious New York attorney Sam is sent t...
4802,Documentary,en,My Date with Drew,1.929883,"rusty bear entertainment, lucky crow films",2005-08-05,NaN,16,"obsession, camcorder, crush, dream girl",Ever since the second grade when he first saw ...,NaN

In [22]:
final_df.isnull().sum()

genres                    0
original_language         0
original_title            0
popularity                0
production_companies      0
release_date              1
tagline                 844
vote_count                0
keywords                  0
overview                  3
tags                    844
dtype: int64

 Drops rows where 'tags' is NaN

In [23]:
final_df = final_df.dropna(subset=['tagline', 'tags','release_date'])

In [24]:
final_df

,genres,original_language,original_title,popularity,production_companies,release_date,tagline,vote_count,keywords,overview,tags
0,"Action, Adventure, Fantasy, Science Fiction",en,Avatar,150.437577,"Ingenious Film Partners, Twentieth Century Fox...",2009-12-10,Enter the World of Pandora.,11800,"culture clash, future, space war, space colony...","In the 22nd century, a paraplegic Marine is di...","In the 22nd century, a paraplegic Marine is di..."
1,"Adventure, Fantasy, Action",en,Pirates of the Caribbean: At World's End,139.082615,"Walt Disney Pictures, Jerry Bruckheimer Films,...",2007-05-19,"At the end of the world, the adventure begins.",4500,"ocean, drug abuse, exotic island, east india t...","Captain Barbossa, long believed to be dead, ha...","Captain Barbossa, long believed to be dead, ha..."
2,"Action, Adventure, Crime",en,Spectre,107.376788,"Columbia Pictures, Danjaq, B24",2015-10-26,A Plan No One Escapes,4466,"spy, based on novel, secret agent, sequel, mi6...",A cryptic message from Bond’s past sends him o...,A cryptic message from Bond’s past sends him o...
3,"Action, Crime, Drama, Thriller",en,The Dark Knight Rises,112.312950,"Legendary Pictures, Warner Bros., DC Entertain...",2012-07-16,The Legend Ends,9106,"dc comics, crime fighter, terrorist, secret id...",Following the death of District Attorney Harve...,Following the death of District Attorney Harve...
4,"Action, Adventure, Science Fiction",en,John Carter,43.926995,Walt Disney Pictures,2012-03-07,"Lost in our world, found in another.",2124,"based on novel, mars, medallion, space travel,...","John Carter is a war-weary, former military ca...","John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...,...,...,...
4795,Drama,en,Bang,0.918116,"Asylum Films, FM Entertainment, Eagle Eye Film...",1995-09-09,Sometimes you've got to break the rules,1,"gang, audition, police fake, homeless, actress",A young woman in L.A. is having a bad day: she...,A young woman in L.A. is having a bad day: she...
4796,"Science Fiction, Drama, Thriller",en,Primer,23.307949,Thinkfilm,2004-10-08,What happens if it actually works?,658,"distrust, garage, identity crisis, time travel...",Friends/fledgling entrepreneurs invent a devic...,Friends/fledgling entrepreneurs invent a devic...
4798,"Action, Crime, Thriller",es,El Mariachi,14.269792,Columbia Pictures,1992-09-04,"He didn't come looking for trouble, but troubl...",238,"united states–mexico barrier, legs, arms, pape...",El Mariachi just wants to play his guitar and ...,El Mariachi just wants to play his guitar and ...
4799,"Comedy, Romance",en,Newlyweds,0.642552,,2011-12-26,A newlywed couple's honeymoon is upended by th...,5,,A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...
4801,,en,Shanghai Calling,0.857008,,2012-05-03,A New Yorker in Shanghai,7,,When ambitious New York attorney Sam is sent t...,When ambitious New York attorney Sam is sent t...

In [25]:
final_df.isnull().sum()

genres                  0
original_language       0
original_title          0
popularity              0
production_companies    0
release_date            0
tagline                 0
vote_count              0
keywords                0
overview                0
tags                    0
dtype: int64

# 🧑‍💻 NLP Vectorization Example

This snippet shows how we use **CountVectorizer** and **NearestNeighbors** from scikit-learn to process movie tags and build a similarity model.

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import NearestNeighbors

In [27]:
vectorizer = CountVectorizer(stop_words='english')
tag_matrix = vectorizer.fit_transform(final_df['tags'])

### 📌 Explanation

CountVectorizer: Transforms text into a bag-of-words representation.

NearestNeighbors: Finds similar movies based on cosine similarity of tag vectors.

In [28]:
knn=NearestNeighbors(metric='cosine',algorithm='brute')
knn.fit(tag_matrix)

NearestNeighbors(algorithm='brute', metric='cosine')

# 🎬 Movie Recommendation Function

This function uses **k-nearest neighbors (KNN)** to recommend movies based on similarity of tags.

In [ ]:
def recommend(movie, n_reco=5, column='original_title'):
    movie_index = final_df[final_df[column] == movie].index[0]
    movie_vector = tag_matrix[movie_index]

    distances, indices = knn.kneighbors(movie_vector, n_neighbors=n_reco+1)

    recommended_indices = indices.flatten()[1:]
    recommended_movies = final_df.iloc[recommended_indices][column]

    print(f"You May Like:")
    for m in recommended_movies:
        print(m)

# Example usage

In [30]:
recommend("The Dark Knight Rises")

You May Like:
The Dark Knight
Batman Begins
Batman
Batman Returns
Batman Forever